# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-03 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodstore',
            name='photo',
            field=models.ImageField(blank=True, upload_to='admin/foodstore'),
        ),
        migrations.AddField(
            model_name='menu',
            name='photo',
            field=models.ImageField(blank=True, upload_to='admin/menu'),
        ),
    ]
