# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-04 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20180103_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodstore',
            name='is_contain_drink',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foodstore',
            name='is_contain_etc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foodstore',
            name='is_contain_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foodstore',
            name='is_contain_side',
            field=models.BooleanField(default=False),
        ),
    ]
