# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-09 04:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yagujango', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0003_auto_20180104_0431'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateMenuLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('remain_amount', models.PositiveIntegerField(default=0)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='DateStoreLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField()),
                ('contact', models.CharField(max_length=20)),
                ('total_price', models.PositiveIntegerField()),
                ('paid_point', models.PositiveIntegerField()),
                ('paid_price', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderedMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Menu')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Order')),
            ],
        ),
        migrations.AddField(
            model_name='foodstore',
            name='stadium',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='yagujango.Stadium'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datestorelimit',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Foodstore'),
        ),
        migrations.AddField(
            model_name='datemenulimit',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.DateStoreLimit'),
        ),
    ]
