# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-09 10:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yagujango', '0001_initial'),
        ('food', '0006_auto_20180109_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_stadium',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='yagujango.Stadium'),
            preserve_default=False,
        ),
    ]
