# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-04 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('en_name', models.CharField(blank=True, max_length=20)),
                ('booking_url', models.CharField(max_length=200)),
                ('basic', models.TextField(blank=True)),
                ('subway', models.TextField(blank=True, help_text='지하철 교통편 입력')),
                ('bus', models.TextField(blank=True, help_text='버스 교통편 입력')),
                ('parking', models.TextField(blank=True, help_text='주차편 입력')),
            ],
        ),
    ]
